-- drop database dbu_employees_db;
create database dbu_employees_db; 
use dbu_employees_db;   

-- MySQL Script generated by MySQL Workbench
-- ዓርብ፣ ጁን 16 ቀን 2023 11:04:43 ከሰዓት EAT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbu_employees_db
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbu_employees_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbu_employees_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbu_employees_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `dbu_employees_db` ;

-- -----------------------------------------------------
-- Table `dbu_employees_db`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbu_employees_db`.`Employees` (
  `employeeID` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `role` VARCHAR(45) NULL DEFAULT NULL,
  `department` VARCHAR(45) NULL DEFAULT NULL,
  `college` VARCHAR(45) NULL DEFAULT NULL,
  `phone_number` VARCHAR(45) NULL DEFAULT NULL,
  UNIQUE INDEX `employeeID_UNIQUE` (`employeeID` ASC) VISIBLE,
  PRIMARY KEY (`employeeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- drop table Employees; 
insert into Employees values('dbur/1212/11', 'Kelem', 'mewerk', 'hwManager', 'ict','computing', '+251966732828');
insert into Employees values('dbur/0482/10', 'Bayulegn', 'Maereg', 'swAgent', 'cs','computing', '+251564732828');
insert into Employees values('dbur/0382/10', 'Bayulegn', 'Maereg', 'user', 'sw','computing', '+251934732828');
select * from Employees;
