-- MySQL Script generated by MySQL Workbench
-- እሑድ፣ ጁን 11 ቀን 2023  1:25:08 ከሰዓት EAT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema helpdesk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema helpdesk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `helpdesk` ;
USE `helpdesk` ;

-- -----------------------------------------------------
-- Table `helpdesk`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpdesk`.`user` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `helpdesk`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpdesk`.`department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(70) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_department_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_department_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `helpdesk`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `helpdesk`.`pending`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpdesk`.`pending` (
  `tempUserName` VARCHAR(50) NOT NULL,
  `tempPass` INT NOT NULL,
  `userName` VARCHAR(50) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `helpdesk`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpdesk`.`employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `department` VARCHAR(45) NULL,
  `office_block` VARCHAR(50) NOT NULL,
  `favorite_number` INT NOT NULL,
  `birth_date` DATE NOT NULL,
  `approve` ENUM('yes', 'no') NOT NULL DEFAULT 'no',
  `new` ENUM('yes', 'no') NOT NULL DEFAULT 'yes',
  `status` ENUM('Accept', 'Reject', 'Pending') NOT NULL DEFAULT 'Pending',
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_employees_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_employees_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `helpdesk`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 61
DEFAULT CHARACTER SET = ucs2;


-- -----------------------------------------------------
-- Table `helpdesk`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpdesk`.`ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NOT NULL,
  `chat` VARCHAR(200) NOT NULL,
  `category` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `helpdesk`.`manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpdesk`.`manager` (
  `id` INT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_manager_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_manager_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `helpdesk`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `helpdesk`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpdesk`.`admin` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_admin_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_admin_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `helpdesk`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `helpdesk`.`resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpdesk`.`resource` (
  `id` INT NOT NULL,
  `resource_name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `helpdesk`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpdesk`.`role` (
  `id` INT NOT NULL,
  `role_name` VARCHAR(45) NULL,
  `view` VARCHAR(45) NULL,
  `add` VARCHAR(45) NULL,
  `edit` VARCHAR(45) NULL,
  `delete` VARCHAR(45) NULL,
  `created_at` VARCHAR(45) NULL,
  `updated_atl` VARCHAR(45) NULL,
  `resource_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `resource_id`, `user_id`),
  INDEX `fk_role_resource_resource1_idx` (`resource_id` ASC) VISIBLE,
  INDEX `fk_role_resource_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_role_resource_resource1`
    FOREIGN KEY (`resource_id`)
    REFERENCES `helpdesk`.`resource` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_resource_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `helpdesk`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
